# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_AUTEUR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class:    UserBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: admin
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:       logout
                target:     login
        admin:
            pattern:   ^/admin
            anonymous: false
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:       logout
                target:     login

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY  }